[env]
TELOXIDE_TOKEN = "7654300172:AAFW3xYYuGuRT3FDHqLklqmFBaVW7PHcp4A"
INBOUND = "http://127.0.0.1:4687/"
OUTBOUND = "https://smee.io/XhYNuoibVe0eddww"
DATABASE_PATH = "sqlite://data/bot_data.db"
RUST_LOG = "info"
